[package]
name = "jrsonnet"
description = "Rust jsonnet implementation"
version.workspace = true
repository.workspace = true
authors = ["Yaroslav Bolyukin <iam@lach.pw>"]
license = "MIT"
edition = "2021"

[features]
experimental = ["exp-preserve-order", "exp-destruct"]
# Use mimalloc as allocator
mimalloc = ["mimallocator"]
# Experimental feature, which allows to preserve order of object fields
exp-preserve-order = ["jrsonnet-evaluator/exp-preserve-order", "jrsonnet-cli/exp-preserve-order"]
# Destructuring of locals
exp-destruct = ["jrsonnet-evaluator/exp-destruct"]
# Iteration over objects yields [key, value] elements
exp-object-iteration = ["jrsonnet-evaluator/exp-object-iteration"]
# Bigint type
exp-bigint = ["jrsonnet-evaluator/exp-bigint", "jrsonnet-cli/exp-bigint"]

# std.thisFile support
legacy-this-file = ["jrsonnet-cli/legacy-this-file"]

nightly = ["jrsonnet-evaluator/nightly"]

[dependencies]
jrsonnet-evaluator.workspace = true
jrsonnet-parser.workspace = true
jrsonnet-cli.workspace = true
jrsonnet-gcmodule.workspace = true

mimallocator = { version = "0.1.3", optional = true }
thiserror = "1.0"
clap = { version = "4.1", features = ["derive"] }
clap_complete = { version = "4.1" }
ass-stroke = { git = "https://github.com/CertainLach/ass-stroke", version = "0.1.0" }
